# Generated by Django 2.0.2 on 2018-05-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smr_pic', models.ImageField(blank=True, upload_to='smr_pics')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=12)),
                ('smr_car', models.CharField(max_length=256)),
                ('smr_franchise', models.ForeignKey(on_delete='PROTECT', related_name='smrs', to='franchises.Franchise')),
            ],
        ),
    ]
