# Generated by Django 2.0.2 on 2018-05-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingteam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smr',
            name='smr_pic',
            field=models.ImageField(blank=True, default='default.png', upload_to='smr_pics'),
        ),
    ]
