# Generated by Django 2.0.2 on 2018-05-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apm_pic', models.ImageField(blank=True, default='default.png', upload_to='apm_pics')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256, null=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('apm_franchise', models.ForeignKey(on_delete='PROTECT', related_name='apms', to='franchises.Franchise')),
            ],
        ),
        migrations.CreateModel(
            name='ProjManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_pic', models.ImageField(blank=True, default='default.png', upload_to='pm_pics')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256, null=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('pm_car', models.CharField(max_length=256)),
                ('pm_franchise', models.ForeignKey(on_delete='PROTECT', related_name='projmanagers', to='franchises.Franchise')),
            ],
        ),
        migrations.AddField(
            model_name='apm',
            name='project_manager',
            field=models.ManyToManyField(related_name='pms', to='office.ProjManager'),
        ),
    ]
