# Generated by Django 2.0.2 on 2018-05-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apm',
            name='project_manager',
            field=models.ManyToManyField(related_name='pms', to='office.Projmanager'),
        ),
    ]
